name: TokenSubmision
version: '${project.version}'
main: me.thelpro.Tokensubmission
api-version: 1.19
authors: [ TheLPro ]
description: Token Submission
commands:
  token:
    description: Submits / imports a token
    usage: /<command> <submit/import> <amount-submit-only)
permissions:
  token.import:
    description: Be able to import tokens.
  token.submit:
    description: Be able to submit tokens.
  token.loginclear:
    description: Get cleared of tokens when you join.
    default: not op